# Site settings
title: DeepDiveData | From Data to Insights 
description: "We love data and viz"
url: "http://deepdivedata.github.io"
author:
  name: "Jansi Thiyagarajan"
  email: "deepdivedata@gmail.com"
  url: "http://www.deepdivedata.github.io"

# Build settings
baseurl: "http://www.deepdivedata.github.io" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
